// Curated list of fragrance brands for seed data
// Categories: Middle Eastern, Pakistani, International/Niche

export const seedBrands = [
  // === MIDDLE EASTERN ===
  "Lattafa",
  "Armaf",
  "Rasasi",
  "Ajmal",
  "Swiss Arabian",
  "Al Haramain",
  "Al Rehab",
  "Milton-Lloyd",
  "Afnan",
  "Maison Alhambra",
  "Paris Corner",
  "Fragrance World",
  "Emir",
  "Franck Olivier",
  "Oud 24 Hours",
  "Al Wataniah",
  "Ameer Al Oudh",
  "Al Naseem",
  "Abdul Samad Al Qurashi",
  "Arabian Oud",
  "Amouage",
  "Initio Parfums Privés",
  "Xerjoff",
  "Memo Paris",
  "Roja Dove",
  "Nishane",
  "Byredo",
  "Bortnikoff",
  "Areej Le Doré",
  "Sultan Pasha Attars",
  "Shaikha",
  "Al Majed Oud",
  "Anfas",
  "Ojar",
  "Ajanta",
  "Al Sharqiah",
  "Al Fares",
  "Bakhoor Al Khaleej",
  "Al Qasmi",
  "Al Shams",

  // === PAKISTANI ===
  "J.",
  "Scentsation",
  "S. & Co.",
  "Bonanza Satrangi",
  "Sapphire",
  "Limelight",
  "Crescent",
  "Splash by S. & Co.",
  "S. & Co. Men",
  "Bareeze",
  "Khaadi",
  "Al Karam",
  "Edenrobe",
  "Gulahmed",
  "Firdous",
  "ChenOne",
  "Generation",
  "Nishat Linen",
  "Outfitters",
  "Teenage",
  "Mushq",
  "Ishq",
  "Suffuse",
  "Scents n Stories",
  "Punjab Perfumes",
  "Pak Perfumes",
  "Al-Nabeel",
  "Al-Mustafa Perfumes",
  "Ibn-e-Safi",
  "Attar Bazaar",
  "Itr-e-Naqvi",
  "Scent & Style",
  "Fogg (Pakistan)",
  "Dunhill (Pakistan Edition)",
  "Boss fragrance (Pakistani variant)",

  // === INTERNATIONAL ===
  "Dior",
  "Chanel",
  "Louis Vuitton",
  "Gucci",
  "Yves Saint Laurent",
  "Tom Ford",
  "Creed",
  "Maison Francis Kurkdjian",
  "Kilian Paris",
  "Jo Malone London",
  "Diptyque",
  "Le Labo",
  "Prada",
  "Valentino",
  "Versace",
  "Dolce & Gabbana",
  "Giorgio Armani",
  "Bvlgari",
  "Burberry",
  "Givenchy",
  "Paco Rabanne",
  "Jean Paul Gaultier",
  "Viktor & Rolf",
  "Calvin Klein",
  "Hugo Boss",
  "Ralph Lauren",
  "Carolina Herrera",
  "Marc Jacobs",
  "Tiffany & Co.",
  "Tous",
  "Bentley",
  "Ferrari",
  "Montblanc",
  "Salvatore Ferragamo",
  "Coach",
  "Michael Kors",
  "Jimmy Choo",
  "Acqua di Parma",
  "Clive Christian",
  "Boadicea the Victorious",
  "Electimuss London",
  "Roja Parfums",
  "Tiziana Terenzi",
  "Profumum Roma",
  "Mancera",
  "Montale",
  "Parfums de Marly",
  "Merchant of Venice",
  "Carner Barcelona",
  "Etat Libre d'Orange",
  "L'Artisan Parfumeur",
  "Serge Lutens",
  "Guerlain",
  "Hermès",
  "Cartier",
  "Chopard",
  "Boucheron",
  "Lalique",
  "Molinard",
  "Thierry Mugler",
  "Nina Ricci",
  "Cacharel",
  "Laura Mercier",
  "Elizabeth Arden",
  "Estée Lauder",
  "Clinique",
  "Tommy Hilfiger",
  "Abercrombie & Fitch",
  "Hollister",
  "Ariana Grande",
  "Britney Spears",
  "Rihanna",
  "Kylie Jenner",
  "Davidoff",
  "Azzaro",
  "Nautica",
  "Police",
  "Benetton",
  "Adidas",
  "Replay",
  "Swiss Army",
];
